<a href="https://colab.research.google.com/github/caramelpopcornKHU/tensorflow/blob/main/02_03_%EB%B8%8C%EB%A1%9C%EB%93%9C%EC%BA%90%EC%8A%A4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(
    [[1, 2, 3],
     [4, 5, 6]]
)
b = tf.constant([1, -1, 2])

print(f"a의 shape: {a.shape}")
print(f"b의 shape: {b.shape}")

a의 shape: (2, 3)
b의 shape: (3,)


shape가 달라서 연산할 수 없는대 연산을 성공적으로함    
R에서 recycling rule 처럼 tensorflow에서 브로드캐스팅으로   
재활용함

In [3]:
a + b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 1, 5],
       [5, 4, 8]], dtype=int32)>

In [4]:
b_expanded = tf.constant(
    [[1, -1, 2],
     [1, -1, 2]]
)
a + b_expanded

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 1, 5],
       [5, 4, 8]], dtype=int32)>

In [ ]:
a = tf.constant(
    [[-1, -1],
     [1, 1]]
)

a tensor에 1씩 증가 시키려면? 어떻게 하죠?

In [5]:
a + 1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>

2배로 증가 시키려면요?

In [6]:
a * 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

a는 **2**차원 탠서   
b는 **1**차원 탠서

In [7]:
a = tf.constant(
    [[1, 2, 3],
     [4, 5, 6]]
)
b = tf.constant([1, -1, 2])

print(f"a의 shape: {a.shape}")
print(f"b의 shape: {b.shape}")

a의 shape: (2, 3)
b의 shape: (3,)


원래라면 계산 안되는 것이 맞잖아?   
하지만 보로드캐스팅 기능은 차원이 작은 것에 맨앞에 1이 붙어   
(3,) -> (1,3)   


```
tf.constant( [1,2,3] )
이게 브로드 캐스팅이 되려면

tf.constant( [[1,2,3]] )
```




In [8]:
b_expanded = tf.constant([[1, -1, 2],
                          [1, -1, 2]])
print(b_expanded.shape)

(2, 3)


브로드캐스팅이 불가능한 경우

In [9]:
a = tf.constant(
    [[1, 2, 3],
     [4, 5, 6]]
)
b = tf.constant([1, -1])

print(f"a의 shape: {a.shape}")
print(f"b의 shape: {b.shape}")

a의 shape: (2, 3)
b의 shape: (2,)


a의 shape: (2, 3)   
b의 shape: (2,)   
   
   브로드캐스팅 하면 1이 차원을 높이며 붙는다고 햇지?   
b의 shape: **(1,2)**

   브로드캐스팅의 2번째 규칙 위의 차원과 맞추기   
b의 shape: **(2,2)**   

(2,3) + (2,2) 는 계산 할 수 없어!

In [10]:
a + b

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} Incompatible shapes: [2,3] vs. [2] [Op:AddV2] name: 

In [ ]:
data0 = [[1,1],
         [-1,-1]]

In [ ]:
data1 = [[1,1],
         [1,1]]

In [ ]:
tensor0 = tf.constant(data0)

In [ ]:
tensor1 = tf.constant(data1)

In [ ]:
print((tensor0 + tensor1).numpy())

[[2 2]
 [0 0]]
