<a href="https://colab.research.google.com/github/caramelpopcornKHU/tensorflow/blob/main/02_01_%ED%85%90%EC%84%9C_%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
!python3 --version


Python 3.11.13


In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
tensor = tf.constant([1, 2])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
print(f"data type: {tensor.dtype}")
print(f"number of dimensions: {tensor.ndim}")
print(f"shape: {tensor.shape}")

data type: <dtype: 'int32'>
number of dimensions: 1
shape: (2,)


In [ ]:
tensor = tf.constant([1, 1.5])
tensor.dtype

tf.float32

dtype을 설정해주지 않으면 자동으로 감지, dtype을 설정해주면 그것으로 됨

In [ ]:
tensor = tf.constant([1, 2], dtype=tf.float16)
tensor.dtype

tf.float16

In [ ]:
import numpy as np

tensor = tf.constant(
    np.array([[1, 2], [3, 4]])
)
tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [ ]:
variable_tensor = tf.Variable([1, 2])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
variable_tensor = tf.Variable(
    np.array([[1, 2], [3, 4]])
)
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [ ]:
variable_tensor.assign(
    [[4, 5], [6, 7]]
)
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[4, 5],
       [6, 7]])>

표준정규분포 난수 텐서

In [ ]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.1939218 , -1.1299673 , -0.21219793],
       [-1.6194668 , -1.148304  , -0.9480288 ],
       [ 0.73439586,  1.1533499 , -0.7385553 ]], dtype=float32)>

In [ ]:
tf.random.normal([2,3],mean=3,stddev=2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5.2250876 ,  3.6995604 , -0.20966935],
       [ 1.0065567 ,  3.2205925 ,  3.0883653 ]], dtype=float32)>

uniform distribution

In [ ]:
tf.random.uniform([2,2,3,4])

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0.89787996, 0.13944685, 0.6851301 , 0.5092598 ],
         [0.90597034, 0.75344586, 0.3466345 , 0.1936593 ],
         [0.69914865, 0.41974735, 0.7310879 , 0.38692772]],

        [[0.9495847 , 0.10521805, 0.11744988, 0.59081805],
         [0.5550389 , 0.2914306 , 0.63665926, 0.94189477],
         [0.8319882 , 0.6840172 , 0.4843198 , 0.8120154 ]]],


       [[[0.49578738, 0.8984773 , 0.7385448 , 0.2824849 ],
         [0.2379359 , 0.62189496, 0.6681738 , 0.19907022],
         [0.55414915, 0.74857235, 0.92656076, 0.4343747 ]],

        [[0.62351   , 0.78326523, 0.02504349, 0.77474105],
         [0.79710686, 0.47125447, 0.44781375, 0.6942251 ],
         [0.00844371, 0.07155478, 0.2834673 , 0.22104704]]]],
      dtype=float32)>

In [ ]:
tf.random.uniform([1, 3], minval=-3, maxval=3)


<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-1.0749464 ,  2.6919022 ,  0.82402325]], dtype=float32)>

ones() 함수는 값이 전부 1인 텐서

In [ ]:
tf.ones([1, 3])


<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([1, 3])


<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>

In [ ]:
tf.fill([2, 3], 10)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10]], dtype=int32)>