<a href="https://colab.research.google.com/github/caramelpopcornKHU/tensorflow/blob/main/02_04_Dataset_%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = np.array([0, 1, 2, 3, 4])

dataset 객체를 Dataset.from_tensor_slices함수로 만드면됨

In [3]:
dataset = tf.data.Dataset.from_tensor_slices(x)

In [4]:
for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)


In [5]:
x = [[10, 20],
     [20, 15],
     [15, 15],
     [80, 90],
     [85, 80],
     [85, 90]]

In [6]:
dataset = tf.data.Dataset.from_tensor_slices(x)

In [7]:
for data in dataset:
    print(data)

tf.Tensor([10 20], shape=(2,), dtype=int32)
tf.Tensor([20 15], shape=(2,), dtype=int32)
tf.Tensor([15 15], shape=(2,), dtype=int32)
tf.Tensor([80 90], shape=(2,), dtype=int32)
tf.Tensor([85 80], shape=(2,), dtype=int32)
tf.Tensor([85 90], shape=(2,), dtype=int32)


In [8]:
x = [[10, 20],
     [20, 15],
     [15, 15],
     [80, 90],
     [85, 80],
     [85, 90]]

y = [0, 0, 0, 1, 1, 1]

x리스트 y리스트를 튜플로 묶어서 넘기기

In [9]:
dataset = tf.data.Dataset.from_tensor_slices((x, y))

동일한 인덱스에서 x와 y가 묶여있음

In [10]:
for data in dataset:
    print(data)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 15], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([15, 15], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([80, 90], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([85, 80], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([85, 90], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)


In [11]:
for data in dataset:
    print(f"x: {data[0]}, y: {data[1]}")

x: [10 20], y: 0
x: [20 15], y: 0
x: [15 15], y: 0
x: [80 90], y: 1
x: [85 80], y: 1
x: [85 90], y: 1


In [12]:
import keras

In [13]:
train_data, test_data = keras.datasets.california_housing.load_data()

x_train, y_train = train_data
x_test, y_test = test_data

743530/743530 ━━━━━━━━━━━━━━━━━━━━ 1s 1us/step


In [22]:
train_data

(<tf.Tensor: shape=(8,), dtype=float32, numpy=
 array([-118.27  ,   34.09  ,   52.    , 2327.    ,  555.    , 1048.    ,
         491.    ,    3.7847], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=252300.0>)

In [23]:
x_train

array([[-118.27  ,   34.09  ,   52.    , ..., 1048.    ,  491.    ,
           3.7847],
       [-118.36  ,   33.96  ,   21.    , ..., 1286.    ,  557.    ,
           2.7284],
       [-122.39  ,   37.76  ,   52.    , ...,  712.    ,  398.    ,
           3.9722],
       ...,
       [-122.34  ,   37.57  ,   52.    , ...,  876.    ,  359.    ,
           8.2598],
       [-122.18  ,   37.89  ,   18.    , ..., 1634.    ,  734.    ,
           8.1489],
       [-118.43  ,   34.2   ,   29.    , ..., 1942.    ,  679.    ,
           3.1118]], dtype=float32)

In [14]:
(x_train, y_train), (x_test, y_test) = keras.datasets.california_housing.load_data()

In [15]:
x_train[0]

array([-118.27  ,   34.09  ,   52.    , 2327.    ,  555.    , 1048.    ,
        491.    ,    3.7847], dtype=float32)

In [16]:
y_train[0]

np.float32(252300.0)

In [17]:
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))

In [18]:
for train_data in train_dataset:
    print(train_data)
    break

(<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-118.27  ,   34.09  ,   52.    , 2327.    ,  555.    , 1048.    ,
        491.    ,    3.7847], dtype=float32)>, <tf.Tensor: shape=(), dtype=float32, numpy=252300.0>)


In [19]:
x = [1,2,3,4,5]
y = [-1,-2,-3,-4,-5]
(x,y)

([1, 2, 3, 4, 5], [-1, -2, -3, -4, -5])

In [20]:
dataset = tf.data.Dataset.from_tensor_slices((x,y))

In [21]:
for data in dataset:
    print(f"{data[0].numpy()}, {data[1].numpy()}")

1, -1
2, -2
3, -3
4, -4
5, -5
