<a href="https://colab.research.google.com/github/caramelpopcornKHU/tensorflow/blob/main/02_02_%E1%84%90%E1%85%A6%E1%86%AB%E1%84%89%E1%85%A5%E1%84%8B%E1%85%B4_%E1%84%87%E1%85%A7%E1%86%AB%E1%84%92%E1%85%AA%E1%86%AB%E1%84%80%E1%85%AA_%E1%84%8B%E1%85%A7%E1%86%AB%E1%84%89%E1%85%A1%E1%86%AB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
!python -V

Python 3.11.13


In [3]:
tf.__version__

'2.18.0'

In [4]:
tensor = tf.constant(
	   [[1, 2],
	    [3, 4]]
)

이게 더 많이 쓰임

In [5]:
np_array = tensor.numpy()
np_array

array([[1, 2],
       [3, 4]], dtype=int32)

In [6]:
type(np_array)

numpy.ndarray

In [7]:
np_array = np.array(tensor)
np_array

array([[1, 2],
       [3, 4]], dtype=int32)

In [8]:
type(np_array)

numpy.ndarray

요소별 덧셈

In [9]:
a = tf.constant(
    [[1,2],
     [3,4]]
)

In [10]:
b = tf.constant(
	   [[1, 1],
	    [2, 2]]
)

In [11]:
add_result = a + b
add_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [12]:
add_result = tf.add(a, b)
add_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

요소별 곱셈   -   이거 행렬곱 아님

'''1x1    2x1    
3x2    4x2'''

In [13]:
mul_result = a * b
mul_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 8]], dtype=int32)>

In [14]:
mul_result = tf.multiply(a, b)
mul_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 8]], dtype=int32)>

In [15]:
a = tf.constant(
    [[1, 2],
     [3, 4],
     [5, 6],
     [7, 8]]
)

b = tf.constant(
    [[1, 0, 0],
     [0, 0, 1],
     [1, 1, 0]]
)

print(f"a의 열 개수: {a.shape[1]}")
print(f"b의 행 개수: {b.shape[0]}")

a의 열 개수: 2
b의 행 개수: 3


이게 행렬곱   
matmul 함수써야 행렬곱

In [16]:
matmul_result = tf.matmul(a, b)
matmul_result

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [4,2], In[1]: [3,3] [Op:MatMul] name: 

In [19]:
aa = tf.constant(
    [
        [0,1],
        [2,3],
        [4,5],
        [6,7]
    ]
)

bb = tf.constant(
    [
        [0,1,2,3],
        [4,5,6,7]
    ]
)

tf.matmul(aa, bb)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47],
       [28, 41, 54, 67]], dtype=int32)>

In [17]:
a = tf.constant(
    [[1, 2],
     [3, 4],
     [5, 6],
     [7, 8]]
)

b = tf.constant(
    [[1, 0, 0],
     [0, 0, 1]]
)


print(f"a의 열 개수: {a.shape[1]}")
print(f"b의 행 개수: {b.shape[0]}")

a의 열 개수: 2
b의 행 개수: 2


In [18]:
matmul_result = tf.matmul(a, b)
matmul_result

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 0, 2],
       [3, 0, 4],
       [5, 0, 6],
       [7, 0, 8]], dtype=int32)>

Data type을 다르게 해서 탠서 2개 생성

In [20]:
tensor_int = tf.constant([1, 2], dtype=tf.int32)
tensor_float = tf.constant([3, 4], dtype=tf.float32)

In [21]:
tensor_int + tensor_float

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 

둘이 타입이 달라

In [22]:
tensor_cast = tf.cast(tensor_float, dtype=tf.int32)
tensor_int + tensor_cast

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

슬라이싱 하는 방법

In [23]:
tensor = tf.constant([3, 5, 7, 9, 10])

In [24]:
tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [25]:
tensor[0].numpy()

np.int32(3)

In [26]:
tensor[-1].numpy()

np.int32(10)

2번 인덱스 전까지

In [27]:
tensor[:2].numpy()

array([3, 5], dtype=int32)

In [28]:
# stride
tensor[::2].numpy()

array([ 3,  7, 10], dtype=int32)

In [29]:
tensor[::-1].numpy()

array([10,  9,  7,  5,  3], dtype=int32)