<a href="https://colab.research.google.com/github/caramelpopcornKHU/tensorflow/blob/main/03_01_Keras_%EC%86%8C%EA%B0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

fc.svg

In [1]:
import tensorflow as tf

keras를 이용하지 않고 Fully connected layer 구현

In [2]:
class FullyConnectedLayer:
    def __init__(self, input_dim, output_dim):
        #가중치
        self.W = tf.Variable(tf.random.normal([input_dim, output_dim]))
        #편향
        self.b = tf.Variable(tf.random.normal([output_dim]))

    def __call__(self, x):
        # 가중치와 값을 행렬곱 + 편향
        return tf.matmul(x, self.W) + self.b

layer = FullyConnectedLayer(8, 4)

In [3]:
import keras

keras에서는 fully connected layer를 dense라고 함

In [4]:
# fully connected layer에서 출력 차원은 4, 활성함수는 relu
layer = keras.layers.Dense(4, activation="relu")

In [10]:
y = layer(tf.random.normal((8,)))

ValueError: Input 0 of layer "dense" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (8,)

tensorflow와 keras에서는 batch size가 꼭 붙어줘야해.   
그래서, 위의 1차원은 안되는 거야.   
      
data가 1000개   
batch size가 100이면   
iteration이 10번

위에 dense layer에 출력차원까지 설정한 객채를 만들었는대, 입력이 없네?    
입력을 만들어서 넣어야지...     
8차원의 input을 넣고 layer 객체 통과해서 y가 나오게 해볼게



```
layer = keras.layers.Dense(4, activation="relu")
```   
출력이 4입니다



In [12]:
tf.random.normal((2,8))

<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[ 2.0530035 ,  0.6641974 , -0.73751724,  0.28468013,  1.6087947 ,
        -0.26025814, -0.8039147 , -1.196801  ],
       [-0.14921516,  0.7299904 , -1.4554627 ,  0.23227817, -0.23816875,
        -0.24932392,  0.21906053,  0.46072653]], dtype=float32)>

In [13]:
x = tf.random.normal([2, 8])
y = layer(x)
y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.        , 0.92051005, 0.        , 0.        ],
       [0.        , 0.06592271, 0.        , 0.98965514]], dtype=float32)>